replicaCount: 1

image:
  repository: kwabsante/go-web-app
  tag: "v1"
  pullPolicy: IfNotPresent

  ingress:
    enabled: false
    cclassName:
    annotations: {}
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific